name: Transaction Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

    //  - name: Simulate Deployment
    //    run: |
      //    echo "Deploying Transaction Service"
        //  sleep 10

        - name: Simulate Deployment
        run: |
          echo "Deploying Transaction Service"
          sleep 10
